"use client";

import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { useBlueprint } from "@/lib/startup/blueprint-context";
import {
  Target,
  Lightbulb,
  Users,
  TrendingUp,
  Star,
  Shield,
  BarChart3,
  Rocket,
  Sparkles,
  LayoutDashboard,
} from "lucide-react";

const iconMap: Record<string, typeof Star> = {
  positive: Lightbulb,
  opportunity: Rocket,
  warning: BarChart3,
  action: Users,
};

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.08 },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 },
};

/* ─── Main Overview Tab ─── */

export function OverviewTab() {
  const { blueprint, generationMode, generationError, generationMetadata } = useBlueprint();
  if (!blueprint) {
    return (
      <EmptyState
        icon={LayoutDashboard}
        title="No blueprint loaded"
        description="Complete the founder interview to see your personalized dashboard with brand score, market fit, insights, and more."
        actionLabel="Start Interview"
        actionHref="/interview"
      />
    );
  }

  const { startupName, companySnapshot, stats, insights } = blueprint;

  const statCards = [
    { label: "Brand Score", value: `${stats.brandScore}`, icon: Star, color: "from-purple-500 to-indigo-600", change: "+8" },
    { label: "Market Fit", value: stats.marketFit, icon: Target, color: "from-blue-500 to-cyan-600", change: "+2" },
    { label: "Readiness", value: `${stats.readiness}%`, icon: Shield, color: "from-emerald-500 to-teal-600", change: "+12%" },
    { label: "Growth Score", value: `${stats.growthScore}`, icon: TrendingUp, color: "from-amber-500 to-orange-600", change: "+5" },
  ];

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="space-y-8"
    >
      {/* Welcome */}
      <motion.div variants={itemVariants}>
        <div className="flex items-center gap-3 mb-2">
          <h1 className="text-2xl sm:text-3xl font-display font-bold">
            Welcome back{startupName ? `, ${startupName.split(" ")[0]}` : ""} 👋
          </h1>
          {generationMetadata && (
            <div className="flex items-center gap-2">
              <Badge variant="default" className="text-[10px] px-1.5 py-0.5 bg-primary/20 text-primary border border-primary/30">
                <Sparkles className="h-3 w-3 mr-1" />
                Generated by {generationMetadata.provider === "groq" ? "Groq" : "DeepSeek"}
              </Badge>
              <span className="text-[10px] text-muted-foreground font-mono">
                {generationMetadata.model}
              </span>
              {generationMetadata.generationTime && (
                <span className="text-[10px] text-muted-foreground">
                  {(generationMetadata.generationTime / 1000).toFixed(1)}s
                </span>
              )}
            </div>
          )}
          {generationError && (
            <Badge variant="outline" className="text-[10px] px-1.5 py-0.5 text-red-400 border-red-500/30">
              AI generation error
            </Badge>
          )}
        </div>
        <p className="text-muted-foreground mt-1">
          Here&apos;s your {startupName || "startup"} dashboard overview.
        </p>
      </motion.div>

      {/* Stats Grid */}
      <motion.div
        variants={itemVariants}
        className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"
      >
        {statCards.map((stat) => {
          const Icon = stat.icon;
          return (
            <Card key={stat.label} className="hover:border-primary/20 transition-all duration-300">
              <CardContent className="p-5">
                <div className="flex items-start justify-between">
                  <div className={`flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br ${stat.color} shadow-lg`}>
                    <Icon className="h-5 w-5 text-white" />
                  </div>
                  <Badge variant="success" className="text-[10px] px-1.5 py-0">
                    +{stat.change}
                  </Badge>
                </div>
                <div className="mt-4">
                  <p className="text-2xl font-bold">{stat.value}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">{stat.label}</p>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </motion.div>

      {/* Fallback notification */}
      {generationError && (
        <motion.div variants={itemVariants}>
          <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4">
            <p className="text-xs text-amber-400/80 leading-relaxed">
              {generationError}
            </p>
          </div>
        </motion.div>
      )}

      {/* Insights */}
      <motion.div variants={itemVariants}>
        <h2 className="text-lg font-semibold mb-4">AI Insights</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {insights.map((insight) => {
            const Icon = iconMap[insight.type] || Lightbulb;
            const typeColors: Record<string, string> = {
              positive: "border-emerald-500/20 bg-emerald-500/5",
              opportunity: "border-blue-500/20 bg-blue-500/5",
              warning: "border-amber-500/20 bg-amber-500/5",
              action: "border-purple-500/20 bg-purple-500/5",
            };
            const iconColors: Record<string, string> = {
              positive: "text-emerald-400",
              opportunity: "text-blue-400",
              warning: "text-amber-400",
              action: "text-purple-400",
            };
            return (
              <div
                key={insight.title}
                className={`rounded-xl border p-5 ${typeColors[insight.type]} transition-all duration-300 hover:shadow-lg`}
              >
                <div className="flex items-start gap-3">
                  <Icon className={`h-5 w-5 mt-0.5 shrink-0 ${iconColors[insight.type]}`} />
                  <div>
                    <h3 className="text-sm font-medium text-foreground mb-1">{insight.title}</h3>
                    <p className="text-xs text-muted-foreground leading-relaxed">{insight.description}</p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </motion.div>

      {/* Company Details */}
      <motion.div variants={itemVariants}>
        <Card className="hover:border-primary/20 transition-all duration-300">
          <CardHeader>
            <CardTitle className="text-lg">Company Snapshot</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-6">
              {[
                { label: "Company", value: startupName },
                { label: "Stage", value: companySnapshot.stage },
                { label: "Industry", value: companySnapshot.industry },
                { label: "Funding", value: companySnapshot.funding },
                { label: "Team Size", value: `${companySnapshot.teamSize} people` },
                { label: "Founded", value: companySnapshot.foundedDate },
              ].map((item) => (
                <div key={item.label}>
                  <p className="text-xs text-muted-foreground mb-1">{item.label}</p>
                  <p className="text-sm font-medium">{item.value}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>
    </motion.div>
  );
}
