"use client";

import { motion } from "framer-motion";
import { Sparkles, Scale } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="glass-strong border-b border-glass-border">
        <div className="mx-auto flex h-14 max-w-4xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-6 w-6 items-center justify-center rounded-md bg-gradient-to-br from-primary to-secondary">
              <Sparkles className="h-3 w-3 text-white" />
            </div>
            <span className="text-sm font-bold">
              Startup<span className="text-primary">OS</span>
            </span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <div className="flex items-center gap-3 mb-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10">
              <Scale className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h1 className="text-2xl font-display font-bold">Terms of Service</h1>
              <p className="text-xs text-muted-foreground">Last updated: June 2025</p>
            </div>
          </div>

          <div className="max-w-none space-y-8 text-sm leading-relaxed text-muted-foreground">
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using StartupOS, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
              <p>StartupOS provides AI-powered tools for startup validation, blueprint generation, logo creation, and website generation. We reserve the right to modify or discontinue features with reasonable notice.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">3. User Accounts</h2>
              <p>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information and promptly update it. You may delete your account at any time via account settings.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">4. Acceptable Use</h2>
              <p>You agree not to: use the service for any illegal purpose; attempt to disrupt or compromise the platform; generate content that infringes on others&apos; rights; or use automated scripts to access the API without authorization.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">5. AI-Generated Content</h2>
              <p>Content generated by AI models is provided &quot;as is&quot; for informational purposes. StartupOS does not guarantee the accuracy, completeness, or commercial viability of AI-generated analyses. You should independently verify any strategic decisions.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">6. Intellectual Property</h2>
              <p>You retain ownership of your startup ideas and generated content. StartupOS owns the platform, design, and underlying technology. We do not claim ownership of your data.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">7. Limitation of Liability</h2>
              <p>StartupOS is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the platform, including business decisions based on AI-generated content.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">8. Termination</h2>
              <p>We may suspend or terminate accounts for violations of these terms. You may terminate at any time by deleting your account. Sections on liability and intellectual property survive termination.</p>
            </section>
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">9. Contact</h2>
              <p>For questions about these terms, contact legal@startupos.app.</p>
            </section>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
